Repository accesso-app/backend, pull requests merged in 2021-05, with the labels that each got.

#33 ACC-36 Add detailed installation steps
  README.md
Labels: documentation

#34 feat: upgrade to latest actix web
  Cargo.lock
  api-admin/Cargo.toml
  api-admin/src/main.rs
  api-internal/Cargo.toml
  api-internal/src/generated.rs
  api-internal/src/main.rs
  api-internal/src/routes/oauth/authorize.rs
  api-internal/src/routes/session/create.rs
  api-internal/src/routes/session/delete.rs
  api-internal/src/services/email.rs
  api-internal/src/services/generator.rs
  api-internal/src/session.rs
  api-public/Cargo.toml
  api-public/src/generated.rs
  api-public/src/lib.rs
  api-public/src/main.rs
  api-public/src/routes/oauth/token.rs
  api-public/src/services/email.rs
  api-public/src/services/generator.rs
  core/Cargo.toml
  core/src/app/oauth/authorize.rs
  core/src/app/oauth/exchange.rs
  core/src/app/session.rs
  core/src/contracts/mocks.rs
  core/src/contracts/repo/mod.rs
  core/src/lib.rs
  core/src/models/access_token.rs
  core/src/models/client.rs
  db/Cargo.toml
  db/src/implementation.rs
  db/src/lib.rs
  rust-toolchain.toml
  settings/src/lib.rs
Labels: chore, feature

#35 feature: replace sha with argon2id
  Cargo.lock
  api-admin/Cargo.toml
  api-internal/Cargo.toml
  api-internal/src/services/generator.rs
  api-public/Cargo.toml
  api-public/src/generated.rs
  api-public/src/services/generator.rs
  core/Cargo.toml
  core/src/app/registrator.rs
  core/src/app/session.rs
  core/src/contracts/mocks.rs
  core/src/contracts/secure.rs
  core/src/models/access_token.rs
  core/src/models/client.rs
  core/src/models/mod.rs
  db/Cargo.toml
  db/src/implementation.rs
  db/src/schema.rs
  migrations/2021-05-31-180104_canonical_email/down.sql
  migrations/2021-05-31-180104_canonical_email/up.sql
  settings/Cargo.toml
Labels: feature
