Repository accesso-app/backend, pull requests merged in 2021-07, with the labels that each got.

#47 ACC-41 Добавить таблицу регистрации пользователя в приложении
  db/src/schema.rs
  migrations/2021-07-05-190243_user-registrations-add-pk/down.sql
  migrations/2021-07-05-190243_user-registrations-add-pk/up.sql
Labels: fix

#38 docs(api-admin): add register application method description | openapi docs
  api-admin/openapi.yaml
Labels: API:Admin

#49 ACC-47 add user_registrations to access_tokens
  Cargo.lock
  Cargo.toml
  Dockerfile
  README.md
  api-public/openapi.yaml
  api-public/src/generated.rs
  app/src/oauth/exchange.rs
  core/src/contracts/mod.rs
  core/src/contracts/repo/access_token.rs
  core/src/contracts/repo/auth_code.rs
  core/src/contracts/repo/client.rs
  core/src/contracts/repo/mod.rs
  core/src/contracts/repo/requests.rs
  core/src/contracts/repo/session.rs
  core/src/contracts/repo/user.rs
  core/src/contracts/repo/user_registration.rs
  core/src/models/access_token.rs
  core/src/models/mod.rs
  core/src/models/user_registration.rs
  db/src/entities/access_token.rs
  db/src/entities/mod.rs
  db/src/entities/user_registration.rs
  db/src/mappers.rs
  db/src/repos/access_token.rs
  db/src/repos/auth_code.rs
  db/src/repos/client.rs
  db/src/repos/mod.rs
  db/src/repos/requests.rs
  db/src/repos/session.rs
  db/src/repos/user.rs
  db/src/repos/user_registration.rs
  justfile
  migrations/20210710070705_add_registration_to_access_tokens.down.sql
  migrations/20210710070705_add_registration_to_access_tokens.up.sql
  migrations/20210710101805_user_registrations_should_use_timestamptz.down.sql
  migrations/20210710101805_user_registrations_should_use_timestamptz.up.sql
  sqlx-data.json
  tests/Cargo.toml
  tests/tests/authorization_test.rs
Labels: refactor

#52 ACC-100 Create table for accesso-admin's token sessions
  migrations/20210717161239_add-admin-session-tokens.down.sql
  migrations/20210717161239_add-admin-session-tokens.up.sql
Labels: feature

#53 Bunch of changes to integrate cardbox auth in accesso
  api-admin/openapi.yaml
  api-internal/openapi.yaml
  api-internal/src/generated.rs
  api-internal/src/main.rs
  api-internal/src/routes/application/get.rs
  api-internal/src/routes/application/mod.rs
  api-internal/src/routes/mod.rs
  api-internal/src/session.rs
  api-public/openapi.yaml
  app/src/application.rs
  app/src/lib.rs
  app/src/oauth/authorize.rs
  app/src/oauth/exchange.rs
  config/admin-development.toml
  config/default-development.toml
  config/default.toml
  config/public-development.toml
  core/src/app/application.rs
  core/src/app/mod.rs
  core/src/app/oauth/authorize.rs
  core/src/app/oauth/exchange.rs
  core/src/contracts/mod.rs
  core/src/contracts/repo/application.rs
  core/src/contracts/repo/client.rs
  core/src/contracts/repo/mod.rs
  core/src/contracts/repo/user_registration.rs
  core/src/models/client.rs
  core/src/services/email.rs
  db/src/entities/client.rs
  db/src/repos/client.rs
  db/src/repos/user_registration.rs
  migrations/20210708091727_add_access_tokens.up.sql
  migrations/20210708091748_add_authorization_codes.up.sql
  migrations/20210708091847_add_session_tokens.up.sql
  migrations/20210708092444_add_user_registrations.up.sql
  migrations/20210710070705_add_registration_to_access_tokens.up.sql
  migrations/20210726090858_add_cardbox_dev_client.down.sql
  migrations/20210726090858_add_cardbox_dev_client.up.sql
  settings/src/lib.rs
Labels: feature
